require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'xCleaner' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
          permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"

                     pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  pod 'nodejs-mobile-react-native', :path => '../node_modules/nodejs-mobile-react-native'

  pod 'react-native-video', :path => '../node_modules/react-native-video'





  target 'xCleanerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
     use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' }) # update this part

  post_install do |installer|
    react_native_post_install(installer)
  end
end
